framework:
    messenger:
        transports:
          async: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
        
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: 'jsonld'
        
        routing:
            'App\Message\AddPropertyMessage' : async
