framework:
    workflows: 
       create_property:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Property
            initial_marking: draft
            places:
                - draft
                - reviewing
                - published
                - rejected
            transitions:
                review: 
                    guard: "is_fully_authenticated() and is_granted('ROLE_PROPRIO')"
                    from: draft
                    to: reviewing
                publish:
                    guard: "is_fully_authenticated() and is_granted('ROLE_ADMIN')"
                    from: reviewing
                    to: published
                rejected:
                    guard: "is_fully_authenticated() and is_granted('ROLE_ADMIN')"
                    from: reviewing
                    to: rejected